config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
   resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  # dose.cocktail
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => "ingredient_id"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
    #@ingredients = @doses.ingredients
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

private
  def  set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find (params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

private
  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])

    @ingredient = Ingredient.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])

  end

private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1>My list of cocktails</h1>
<div>
    <% @cocktails.each do |cocktail| %>
    <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
    <% end %>
    <%= link_to "Add a new cocktail", new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>New cocktail</h1>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>

        <%= f.submit "Add a cocktail", class: "btn btn-primary" %>
        <% end %>
          <%= link_to "Back to list", cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
<h1><%= @cocktail.name %></h1>
</div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
<h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
<% @cocktail.doses.each do |dose| %>
<tr>
    <td><%= dose.ingredient.name %></td>
     <td><%= dose.description %></td>
     <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
  <% end %>
  </td>
</tr>
 <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
<%= link_to "Add dose and ingredients", new_cocktail_dose_path(@cocktail)  %>

<%= link_to "Back to list", cocktails_path %>
<br>
    </div>
  </div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.input :description %>
<%#= f.input :cocktail_id, :as => :hidden, :input_html => { :value => @cocktail.id } %>
<%= f.input :ingredient_id, collection: Ingredient.all, label_method: :name, value_method: :id, include_blank: false%>
<%= f.submit "Add a dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
 <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>